version: '3'

services:
  elweb:
    build:
      context: .
    ports:
      - 6006:6006
    volumes:
      - ./src:/usr/src/app/src
      - ./stories:/usr/src/app/stories

  elwebtests:
    build:
      context: .
    ports:
      - 8008:8008
    volumes:
      - ./src:/usr/src/app/src
    command: ["npm", "run", "test:watch"]
