import Typography from './Typography';
import Button from './Button';
import Input from './Input';
import Select from './Select';
import Avatar from './Avatar';
import Card from './Card';
import SearchForm from './SearchForm';
import Icon from './Icon';
import Information from './Information';
import Map from './Map';
import List from './List';
import ListItem from './ListItem';
import Data from './Data';
import Profile from './Profile';

Typography();
Button();
Input();
Select();
Avatar();
Card();
SearchForm();
Icon();
Information();
Map();
List();
ListItem();
Data();
Profile();
